- uses: tauri-apps/tauri-action@v0.5.14
  env:
    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    TAURI_PRIVATE_KEY: ${{ secrets.TAURI_PRIVATE_KEY }}
    TAURI_KEY_PASSWORD: ${{ secrets.TAURI_KEY_PASSWORD }}
  with:
    tagName: ${{ github.ref_name }}
    releaseName: 'Aisle3 v__VERSION__'
    releaseBody: 'See the assets to download and install this version.'
    releaseDraft: false
    prerelease: false
    includeUpdaterJson: true
    includeDebug: false
    includeRelease: true