name: Tests

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  javascript-tests:
    name: JavaScript & Svelte Tests
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        node-version: [18, 20]
        
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Setup Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
          
      - name: Install dependencies
        run: npm ci
        
      - name: Run TypeScript/Svelte linting
        run: npm run check
        
      - name: Run all JavaScript/Svelte tests (616 tests)
        run: npm run test:run
        
      - name: Generate coverage report
        if: matrix.node-version == 20  # Only generate coverage once
        run: npm run test:run -- --coverage
        
      - name: Upload coverage to Codecov
        if: matrix.node-version == 20
        uses: codecov/codecov-action@v4
        with:
          file: ./coverage/lcov.info
          flags: javascript
          name: javascript-coverage
          
  rust-tests:
    name: Rust Tests & Linting
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libgtk-3-dev libwebkit2gtk-4.1-dev libappindicator3-dev librsvg2-dev patchelf
          
      - name: Setup Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          components: rustfmt, clippy
          override: true
          
      - name: Cache Rust dependencies
        uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            src-tauri/target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
          
      - name: Check Rust formatting
        run: cd src-tauri && cargo fmt --all -- --check
        
      - name: Run Clippy linting
        run: cd src-tauri && cargo clippy --all-targets --all-features -- -D warnings
        
      - name: Run Rust tests (43 tests)
        run: cd src-tauri && cargo test --verbose
        
      - name: Generate Rust coverage
        run: |
          cd src-tauri
          cargo install cargo-tarpaulin
          cargo tarpaulin --verbose --all-features --workspace --timeout 120 --out xml
        continue-on-error: true  # Coverage is optional
          
      - name: Upload Rust coverage to Codecov
        uses: codecov/codecov-action@v4
        with:
          file: ./src-tauri/cobertura.xml
          flags: rust
          name: rust-coverage

  cross-platform-builds:
    name: Cross-Platform Build Tests
    runs-on: ${{ matrix.platform }}
    
    strategy:
      fail-fast: false
      matrix:
        platform: [macos-latest, ubuntu-latest, windows-latest]
        
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'
          
      - name: Setup Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          
      - name: Install system dependencies (Ubuntu)
        if: matrix.platform == 'ubuntu-latest'
        run: |
          sudo apt-get update
          sudo apt-get install -y libgtk-3-dev libwebkit2gtk-4.1-dev libappindicator3-dev librsvg2-dev patchelf
          
      - name: Install JavaScript dependencies
        run: npm ci
        
      - name: Build frontend
        run: npm run build
        
      - name: Test Tauri compilation
        run: cd src-tauri && cargo build

  security-audit:
    name: Security Audit
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'
          
      - name: Setup Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          
      - name: Install JavaScript dependencies
        run: npm ci
        
      - name: Audit JavaScript dependencies
        run: npm audit --audit-level moderate
        
      - name: Audit Rust dependencies
        run: |
          cargo install cargo-audit
          cd src-tauri && cargo audit